### ISSUE TITLE
JDBC connection 

### ISSUE THREAD

**Issue by VivekBasidoni** [Accenture/DBTestCompare#7]
Unable to connect to SQL Server.
I have kept sqljdbc41.jar file in  /jdbc_drivers path.
But it is showing Classnotfoundexception for Class com.microsoft.sqlserver.jdbc.SQLServerDriver.
 <datasource maxPollSize="6">
            <name>SQL_SERVER</name>
            <driver>com.microsoft.sqlserver.jdbc.SQLServerDriver</driver>
            <url>jdbc:sqlserver://172.22.238.XX\MyDB;databaseName=Travel</url>
            <user>XXXX</user>
            <password>XXXX</password>
        </datasource>

It is working with mysql database.So are you loading the jars in the jdbc_driver folder at run time?

![image](https://cloud.githubusercontent.com/assets/17848343/21219061/2afc3e8e-c2d9-11e6-9e01-7341f0ed6199.png)

**Comment by raczeja** [comment]
please use "sqljdbc4.jar" instead of sqljdbc41.jar https://github.com/ObjectivityLtd/DBTestCompare/wiki/Deploying-licensed-jdbc-drivers-(not-open-source)

**Comment by VivekBasidoni** [comment]
Ya it is working now thank you
